# Generated by Django 5.2.14 on 2026-05-21 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntingClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the hunting club or lease.', max_length=200)),
                ('join_code', models.CharField(help_text='Unique code for members to join.', max_length=12, unique=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_clubs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HuntLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_zone', models.CharField(blank=True, help_text="General area e.g., 'North Ridge' or 'Stand 4'", max_length=100)),
                ('bucks_seen', models.IntegerField(default=0)),
                ('does_seen', models.IntegerField(default=0)),
                ('fawns_seen', models.IntegerField(default=0)),
                ('unknown_seen', models.IntegerField(default=0)),
                ('visibility_level', models.IntegerField(choices=[(0, 'Private (Only Me)'), (1, 'Masked/Aggregated (Hide Location)'), (2, 'Full Club (Share Everything)')], default=0)),
                ('notes', models.TextField(blank=True, help_text='General observations (weather, wind, sign, acorns, etc.)')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_hunts', to='hunt_logs.huntingclub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('Buck', 'Buck'), ('Doe', 'Doe')], max_length=10)),
                ('weight_lbs', models.DecimalField(decimal_places=2, help_text='Weight in pounds', max_digits=5)),
                ('is_dressed', models.BooleanField(default=False, verbose_name='Field Dressed?')),
                ('points_left', models.IntegerField(blank=True, default=0)),
                ('points_right', models.IntegerField(blank=True, default=0)),
                ('notes', models.TextField(blank=True, help_text='Shot placement, recovery tracking details, etc.')),
                ('hunt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harvest', to='hunt_logs.huntlog')),
            ],
        ),
    ]
