# Generated by Django 5.2.14 on 2026-05-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='inside_spread',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
